/*
 * Copyright (c) 2025 Andrei Buneyeu
 *
 * This file is part of Kopus and is released under the MIT License.
 * See the LICENSE file for details.
 */
package eu.buney.kopus

// Error codes
const val OPUS_OK = 0
const val OPUS_BAD_ARG = -1
const val OPUS_BUFFER_TOO_SMALL = -2
const val OPUS_INTERNAL_ERROR = -3
const val OPUS_INVALID_PACKET = -4
const val OPUS_UNIMPLEMENTED = -5
const val OPUS_INVALID_STATE = -6
const val OPUS_ALLOC_FAIL = -7

// Encoder CTL request constants
const val OPUS_SET_APPLICATION_REQUEST = 4000
const val OPUS_GET_APPLICATION_REQUEST = 4001
const val OPUS_SET_BITRATE_REQUEST = 4002
const val OPUS_GET_BITRATE_REQUEST = 4003
const val OPUS_SET_MAX_BANDWIDTH_REQUEST = 4004
const val OPUS_GET_MAX_BANDWIDTH_REQUEST = 4005
const val OPUS_SET_VBR_REQUEST = 4006
const val OPUS_GET_VBR_REQUEST = 4007
const val OPUS_SET_BANDWIDTH_REQUEST = 4008
const val OPUS_GET_BANDWIDTH_REQUEST = 4009
const val OPUS_SET_COMPLEXITY_REQUEST = 4010
const val OPUS_GET_COMPLEXITY_REQUEST = 4011
const val OPUS_SET_INBAND_FEC_REQUEST = 4012
const val OPUS_GET_INBAND_FEC_REQUEST = 4013
const val OPUS_SET_PACKET_LOSS_PERC_REQUEST = 4014
const val OPUS_GET_PACKET_LOSS_PERC_REQUEST = 4015
const val OPUS_SET_DTX_REQUEST = 4016
const val OPUS_GET_DTX_REQUEST = 4017
const val OPUS_SET_VBR_CONSTRAINT_REQUEST = 4020
const val OPUS_GET_VBR_CONSTRAINT_REQUEST = 4021
const val OPUS_SET_FORCE_CHANNELS_REQUEST = 4022
const val OPUS_GET_FORCE_CHANNELS_REQUEST = 4023
const val OPUS_SET_SIGNAL_REQUEST = 4024
const val OPUS_GET_SIGNAL_REQUEST = 4025
const val OPUS_GET_LOOKAHEAD_REQUEST = 4027
const val OPUS_RESET_STATE = 4028
const val OPUS_GET_SAMPLE_RATE_REQUEST = 4029
const val OPUS_GET_FINAL_RANGE_REQUEST = 4031
const val OPUS_GET_PITCH_REQUEST = 4033
const val OPUS_SET_GAIN_REQUEST = 4034
const val OPUS_GET_GAIN_REQUEST = 4045
const val OPUS_SET_LSB_DEPTH_REQUEST = 4036
const val OPUS_GET_LSB_DEPTH_REQUEST = 4037
const val OPUS_GET_LAST_PACKET_DURATION_REQUEST = 4039
const val OPUS_SET_EXPERT_FRAME_DURATION_REQUEST = 4040
const val OPUS_GET_EXPERT_FRAME_DURATION_REQUEST = 4041
const val OPUS_SET_PREDICTION_DISABLED_REQUEST = 4042
const val OPUS_GET_PREDICTION_DISABLED_REQUEST = 4043
const val OPUS_SET_PHASE_INVERSION_DISABLED_REQUEST = 4046
const val OPUS_GET_PHASE_INVERSION_DISABLED_REQUEST = 4047
const val OPUS_GET_IN_DTX_REQUEST = 4049
const val OPUS_SET_DRED_DURATION_REQUEST = 4050
const val OPUS_GET_DRED_DURATION_REQUEST = 4051
const val OPUS_SET_DNN_BLOB_REQUEST = 4052

// Opus specific values
const val OPUS_AUTO = -1000
const val OPUS_BITRATE_MAX = -1

// Application types
const val OPUS_APPLICATION_VOIP = 2048
const val OPUS_APPLICATION_AUDIO = 2049
const val OPUS_APPLICATION_RESTRICTED_LOWDELAY = 2051

// Signal types
const val OPUS_SIGNAL_VOICE = 3001
const val OPUS_SIGNAL_MUSIC = 3002

// Bandwidth types
const val OPUS_BANDWIDTH_NARROWBAND = 1101
const val OPUS_BANDWIDTH_MEDIUMBAND = 1102
const val OPUS_BANDWIDTH_WIDEBAND = 1103
const val OPUS_BANDWIDTH_SUPERWIDEBAND = 1104
const val OPUS_BANDWIDTH_FULLBAND = 1105

// Frame sizes
const val OPUS_FRAMESIZE_ARG = 5000
const val OPUS_FRAMESIZE_2_5_MS = 5001
const val OPUS_FRAMESIZE_5_MS = 5002
const val OPUS_FRAMESIZE_10_MS = 5003
const val OPUS_FRAMESIZE_20_MS = 5004
const val OPUS_FRAMESIZE_40_MS = 5005
const val OPUS_FRAMESIZE_60_MS = 5006
const val OPUS_FRAMESIZE_80_MS = 5007
const val OPUS_FRAMESIZE_100_MS = 5008
const val OPUS_FRAMESIZE_120_MS = 5009

// Maximum packet buffer size
// According to the Opus spec, 1276 bytes is enough for a single maximum-size frame
// Using 1276 * 3 = 3828 bytes to safely handle larger packet sizes including
// multi-frame packets and padding (rounded to 4000 for simplicity)
const val DEFAULT_MAX_BYTES = 4000

// Multistream CTL request constants
const val OPUS_MULTISTREAM_GET_ENCODER_STATE_REQUEST = 5120
const val OPUS_MULTISTREAM_GET_DECODER_STATE_REQUEST = 5122
